General:
  Wait After Start: 15

Credentials:
  Username: root
  Use Keyring: true

Network:
  SSH:
    Guest:
      Port: 22
    Host:
      Initial Port: 49152

Virtualizers:
  Windows:
    VirtualBox:
      - $PROGRAMW6432\Oracle\VirtualBox\VBoxManage.exe
      - $PROGRAMFILES\Oracle\VirtualBox\VBoxManage.exe

Package Managers:
  Ubuntu:
    Apt: apt-get

Shells:
  Linux: Posix
  Arch: Posix
  Ubuntu: Posix
  Red Hat: Posix
  Debian: Posix
  Fedora: Posix
  Gentoo: Posix
  openSUSE: Posix
  Mandriva: Posix
  Turbolinux: Posix
  Xandros: Posix
  Oracle: Posix

Machines:
